[options]
standard = "2008"

[libraries]
osvvm.files = [
    "OsvvmLibraries/src/osvvm/*.vhd"
]

osvvm_common.files = [
    "OsvvmLibraries/src/common/src/*.vhd"
]

project.files = [
    "src/*/hdl_src/*.vhd",
    "src/*/hdl_tb/*.vhd"
]
