style: jcl

rule:
  # variable_007: Remove default assignment from variables
  variable_007:
    disable: true

  # signal_007: Remove default assignment from signals
  signal_007:
    disable: true

  # instantiation_034: Prefer component instantiation over direct entity instantiation
  instantiation_034:
    disable: true

  # instantiation_036: Add architecture identifier to entity instantiation
  # instantiation_036:
  #   disable: true

  # loop_statement_201: Insert blank line below loop statement (e.g., after "for")
  loop_statement_201:
    disable: true

  # loop_statement_202: Insert blank line above loop end statement (e.g., before "end loop")
  loop_statement_202:
    disable: true

  # function_006: Insert blank line above function declaration
  function_006:
    disable: true

  # case_200: Insert blank line below case/when statement
  case_200:
    disable: true

  # type_010: Insert blank line above type declaration
  type_010:
    disable: true

  # subtype_201: Insert blank line above subtype declaration
  subtype_201:
    disable: true

  # subtype_202: Insert blank line below subtype declaration
  subtype_202:
    disable: true

  # case_012: Move code after the => to the next line
  case_012:
    disable: true

  # case_201: Insert blank line above when statement
  case_201:
    disable: true

  # case_007: Insert blank line above case statement
  case_007:
    disable: true

  # case_009: Insert blank line above end case
  case_009:
    disable: true

  # case_010: Insert blank line below end case
  case_010:
    disable: true

  # procedure_200: Insert blank line above procedure declaration
  procedure_200:
    disable: true

  # if_007: Remove blank line(s) before elsif
  if_007:
    disable: true

  # if_010: Remove blank line(s) before else
  if_010:
    disable: true

  # if_008: Remove blank line(s) before end if
  if_008:
    disable: true

  # length_001: Reduce line to less than 120 characters
  length_001:
    disable: true

