--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Copyright 2026 Everllence, Teglholmsgade 41, 2450 Copenhagen SV, Denmark
--------------------------------------------------------------------------------------------------------------------------------------------------------------
--
-- Requirements:
--
-- Description: Testbench utility package for the CAN/CAN-FD design.
--              CRC calculation, metadata extraction, and bus stream
--              reference model for simulation verification.
--
-- Revision log:  Date:       Initial:  JIRA:
--                2026-04-10  MRDSA     Extracted from pk_can_types (TB-only utilities)
--------------------------------------------------------------------------------------------------------------------------------------------------------------

