onerror { resume }
set curr_transcript [transcript]
transcript off

add wave -expand -vgroup TB \
	/can_bus_controller_tb/test_id \
	/can_bus_controller_tb/reset_id \
	/can_bus_controller_tb/gen_id \
	/can_bus_controller_tb/rx_sink_fifo_id \
	/can_bus_controller_tb/tx_src_fifo_id \
	/can_bus_controller_tb/rx_2_sink_fifo_id \
	/can_bus_controller_tb/tx_2_src_fifo_id \
	/can_bus_controller_tb/rx_sink_received \
	/can_bus_controller_tb/rx_sink_expected \
	/can_bus_controller_tb/rx_2_sink_received \
	/can_bus_controller_tb/rx_2_sink_expected \
	/can_bus_controller_tb/tx_src_req \
	/can_bus_controller_tb/tx_src_ack \
	/can_bus_controller_tb/tx_2_src_req \
	/can_bus_controller_tb/tx_2_src_ack \
	/can_bus_controller_tb/clk \
	/can_bus_controller_tb/reset \
	/can_bus_controller_tb/rx \
	/can_bus_controller_tb/tx \
	/can_bus_controller_tb/rx_sink_s2d \
	/can_bus_controller_tb/rx_sink_d2s \
	/can_bus_controller_tb/tx_src_s2d \
	/can_bus_controller_tb/tx_src_d2s \
	/can_bus_controller_tb/ack_dut \
	/can_bus_controller_tb/ns_dut \
	/can_bus_controller_tb/rx_2 \
	/can_bus_controller_tb/rx_2i \
	/can_bus_controller_tb/tx_2 \
	/can_bus_controller_tb/tx_2o \
	/can_bus_controller_tb/rx_2_sink_s2d \
	/can_bus_controller_tb/rx_2_sink_d2s \
	/can_bus_controller_tb/tx_2_src_s2d \
	/can_bus_controller_tb/tx_2_src_d2s \
	/can_bus_controller_tb/ack_dut_2 \
	/can_bus_controller_tb/ns_dut_2 \
	/can_bus_controller_tb/disconnect_bus \
	/can_bus_controller_tb/can_bus \
	/can_bus_controller_tb/trans_fast_rx_rec \
	/can_bus_controller_tb/trans_fast_tx_rec \
	/can_bus_controller_tb/trans_norm_rx_rec \
	/can_bus_controller_tb/trans_norm_tx_rec \
	/can_bus_controller_tb/trans_slow_rx_rec \
	/can_bus_controller_tb/trans_slow_tx_rec \
	/can_bus_controller_tb/valid_delay \
	/can_bus_controller_tb/ready_chance \
	/can_bus_controller_tb/can_reset \
	/can_bus_controller_tb/dbg_error_flag \
	/can_bus_controller_tb/al_fsm_state \
	/can_bus_controller_tb/al_sample_rx \
	/can_bus_controller_tb/al_is_transmitter \
	/can_bus_controller_tb/al_transmit \
	/can_bus_controller_tb/al_stuff_bit_valid \
	/can_bus_controller_tb/al_bit_count \
	/can_bus_controller_tb/al_transmit_error_count \
	/can_bus_controller_tb/al_receive_error_count \
	( -vgroup constants \
		/can_bus_controller_tb/gc_TbTimeOut \
		/can_bus_controller_tb/gc_TbClkPeriod \
		/can_bus_controller_tb/gc_verbose \
		/can_bus_controller_tb/c_bit_rate \
		/can_bus_controller_tb/c_phase_seg1_length \
		/can_bus_controller_tb/c_phase_seg2_length \
		/can_bus_controller_tb/c_prop_seg_length \
		/can_bus_controller_tb/c_sync_jump_width \
		/can_bus_controller_tb/c_model_phase_seg1_length \
		/can_bus_controller_tb/c_model_phase_seg2_length \
		/can_bus_controller_tb/c_model_prop_seg_length \
		/can_bus_controller_tb/c_model_sync_jump_width \
		/can_bus_controller_tb/c_bit_length \
		/can_bus_controller_tb/c_clock_delta_1 \
		/can_bus_controller_tb/c_clock_delta_2 \
		/can_bus_controller_tb/c_clock_delta \
	) \
	/can_bus_controller_tb/RV \
	/can_bus_controller_tb/p_main_tester/v_exp_error_counter
add wave -vgroup {Compare tx frame to rx} \
	( -literal /can_bus_controller_tb/u_dut/u_can_serial_to_ast/can_frame ) \
	( -literal /can_bus_controller_tb/p_main_tester/v_ast_frame )
add wave -vgroup tester \
	/can_bus_controller_tb/p_main_tester/v_ast_frame \
	/can_bus_controller_tb/p_main_tester/v_llc_frame \
	/can_bus_controller_tb/p_main_tester/v_llc_w_frame \
	/can_bus_controller_tb/p_main_tester/v_delay \
	/can_bus_controller_tb/p_main_tester/v_loop_counter \
	/can_bus_controller_tb/p_main_tester/v_error_counter \
	/can_bus_controller_tb/p_main_tester/v_error_chance
add wave -expand -vgroup Dut \
	( -vgroup top \
		/can_bus_controller_tb/u_dut/clk_i \
		/can_bus_controller_tb/u_dut/reset_i \
		/can_bus_controller_tb/u_dut/rx_i \
		/can_bus_controller_tb/u_dut/tx_o \
		/can_bus_controller_tb/u_dut/src_s2d_o \
		/can_bus_controller_tb/u_dut/src_d2s_i \
		/can_bus_controller_tb/u_dut/sink_s2d_i \
		/can_bus_controller_tb/u_dut/sink_d2s_o \
		/can_bus_controller_tb/u_dut/ack_o \
		/can_bus_controller_tb/u_dut/ns_o \
		/can_bus_controller_tb/u_dut/stuff_bit \
		/can_bus_controller_tb/u_dut/stuff_bit_valid \
		/can_bus_controller_tb/u_dut/crc \
		/can_bus_controller_tb/u_dut/sta_reset \
		/can_bus_controller_tb/u_dut/ats_ready \
		/can_bus_controller_tb/u_dut/frame_bit \
		/can_bus_controller_tb/u_dut/ats_valid \
		/can_bus_controller_tb/u_dut/ats_reset \
		/can_bus_controller_tb/u_dut/ide \
		/can_bus_controller_tb/u_dut/rtr \
		/can_bus_controller_tb/u_dut/dlc \
		/can_bus_controller_tb/u_dut/sample_rx \
		/can_bus_controller_tb/u_dut/is_transmitter \
		/can_bus_controller_tb/u_dut/can_node_clk_reset \
		/can_bus_controller_tb/u_dut/~ANONYMOUS~0 \
	) \
	( -expand -vgroup fsm \
		/can_bus_controller_tb/u_dut/u_fsm/clk_i \
		/can_bus_controller_tb/u_dut/u_fsm/reset_i \
		/can_bus_controller_tb/u_dut/u_fsm/can_reset_i \
		/can_bus_controller_tb/u_dut/u_fsm/rx_i \
		/can_bus_controller_tb/u_dut/u_fsm/tx_o \
		/can_bus_controller_tb/u_dut/u_fsm/ack_o \
		/can_bus_controller_tb/u_dut/u_fsm/ns_o \
		/can_bus_controller_tb/u_dut/u_fsm/stuff_bit_i \
		/can_bus_controller_tb/u_dut/u_fsm/stuff_bit_valid_i \
		/can_bus_controller_tb/u_dut/u_fsm/frame_in_progress_o \
		/can_bus_controller_tb/u_dut/u_fsm/crc_i \
		/can_bus_controller_tb/u_dut/u_fsm/crc_start_o \
		/can_bus_controller_tb/u_dut/u_fsm/sample_rx_i \
		/can_bus_controller_tb/u_dut/u_fsm/transmit_i \
		/can_bus_controller_tb/u_dut/u_fsm/can_node_clk_reset_o \
		/can_bus_controller_tb/u_dut/u_fsm/sta_reset_o \
		/can_bus_controller_tb/u_dut/u_fsm/sta_ack_o \
		/can_bus_controller_tb/u_dut/u_fsm/ast_ready_o \
		/can_bus_controller_tb/u_dut/u_fsm/is_transmitter_o \
		/can_bus_controller_tb/u_dut/u_fsm/frame_bit_i \
		/can_bus_controller_tb/u_dut/u_fsm/frame_bit_valid_i \
		/can_bus_controller_tb/u_dut/u_fsm/ide_i \
		/can_bus_controller_tb/u_dut/u_fsm/rtr_i \
		/can_bus_controller_tb/u_dut/u_fsm/dlc_i \
		/can_bus_controller_tb/u_dut/u_fsm/ats_reset_o \
		/can_bus_controller_tb/u_dut/u_fsm/debug_error_flag_o \
		/can_bus_controller_tb/u_dut/u_fsm/fsm_state \
		/can_bus_controller_tb/u_dut/u_fsm/node_error_state \
		/can_bus_controller_tb/u_dut/u_fsm/transmit_error_count \
		/can_bus_controller_tb/u_dut/u_fsm/receive_error_count \
		/can_bus_controller_tb/u_dut/u_fsm/bus_off_re_int_count \
		/can_bus_controller_tb/u_dut/u_fsm/bit_count \
		/can_bus_controller_tb/u_dut/u_fsm/transmit_ack \
		/can_bus_controller_tb/u_dut/u_fsm/is_transmitter \
		/can_bus_controller_tb/u_dut/u_fsm/dlc_shift \
		/can_bus_controller_tb/u_dut/u_fsm/rtr_bit \
		/can_bus_controller_tb/u_dut/u_fsm/crc_error \
		/can_bus_controller_tb/u_dut/u_fsm/stuff_bit_error \
		/can_bus_controller_tb/u_dut/u_fsm/do_not_count_stuff_error \
		/can_bus_controller_tb/u_dut/u_fsm/ack_error \
		/can_bus_controller_tb/u_dut/u_fsm/tec_control \
		/can_bus_controller_tb/u_dut/u_fsm/rec_control \
		/can_bus_controller_tb/u_dut/u_fsm/rx_r \
		/can_bus_controller_tb/u_dut/u_fsm/c_bit_count_into_crc \
		/can_bus_controller_tb/u_dut/u_fsm/c_bit_count_into_arb \
	) \
	( -vgroup node_clock \
		/can_bus_controller_tb/u_dut/u_can_node_clock/clk_i \
		/can_bus_controller_tb/u_dut/u_can_node_clock/reset_i \
		/can_bus_controller_tb/u_dut/u_can_node_clock/rx_i \
		/can_bus_controller_tb/u_dut/u_can_node_clock/sample_rx_o \
		/can_bus_controller_tb/u_dut/u_can_node_clock/transmit_o \
		/can_bus_controller_tb/u_dut/u_can_node_clock/segment \
		/can_bus_controller_tb/u_dut/u_can_node_clock/time_quantum_count \
		/can_bus_controller_tb/u_dut/u_can_node_clock/phase_seg1_length \
		/can_bus_controller_tb/u_dut/u_can_node_clock/phase_seg2_length \
		/can_bus_controller_tb/u_dut/u_can_node_clock/clk_div_counter \
		/can_bus_controller_tb/u_dut/u_can_node_clock/rx_prev \
		/can_bus_controller_tb/u_dut/u_can_node_clock/gc_bit_rate_hz \
		/can_bus_controller_tb/u_dut/u_can_node_clock/gc_default_prop_seg_length \
		/can_bus_controller_tb/u_dut/u_can_node_clock/gc_default_phase_seg_1_length \
		/can_bus_controller_tb/u_dut/u_can_node_clock/gc_default_phase_seg_2_length \
		/can_bus_controller_tb/u_dut/u_can_node_clock/gc_sync_jump_width \
		/can_bus_controller_tb/u_dut/u_can_node_clock/c_nominal_time_quanta_per_bit \
		/can_bus_controller_tb/u_dut/u_can_node_clock/c_bit_period \
		/can_bus_controller_tb/u_dut/u_can_node_clock/c_bit_quanta \
		/can_bus_controller_tb/u_dut/u_can_node_clock/c_bit_quanta_cycles \
	) \
	( -vgroup can_ast_to_serial \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/clk_i \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/reset_i \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/frame_bit_valid_o \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/frame_bit_o \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/rtr_bit_o \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/ide_bit_o \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/dlc_bits_o \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/ready_i \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/is_transmitter_i \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/sink_s2d_i \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/sink_d2s_o \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/addr \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/ats_fsm_state \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/load_shift_reg \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/shift_reg \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/shift_left \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/bit_count \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/padding_bits \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/~ANONYMOUS~0 \
		/can_bus_controller_tb/u_dut/u_can_ast_to_serial/~ANONYMOUS~2 \
	) \
	( -vgroup can_serial_to_ast \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/clk_i \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/reset_i \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/valid_i \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/ack_i \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/rx_i \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/src_s2d_o \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/src_d2s_i \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/state \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/bit_count \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/byte_count \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/can_frame \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/frame_valid \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/id \
		/can_bus_controller_tb/u_dut/u_can_serial_to_ast/c_max_byte_cnt \
	) \
	( -vgroup can_stuff_bit_gen \
		/can_bus_controller_tb/u_dut/u_can_stuff_bit_gen/count \
		/can_bus_controller_tb/u_dut/u_can_stuff_bit_gen/reset_i \
		/can_bus_controller_tb/u_dut/u_can_stuff_bit_gen/rx_i \
		/can_bus_controller_tb/u_dut/u_can_stuff_bit_gen/sample_rx_i \
		/can_bus_controller_tb/u_dut/u_can_stuff_bit_gen/stuff_bit_o \
		( -bold /can_bus_controller_tb/u_dut/u_can_stuff_bit_gen/stuff_bit_valid_o ) \
		/can_bus_controller_tb/u_dut/u_can_stuff_bit_gen/rx_prev \
	) \
	( -vgroup can_gen_crc \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/clk_i \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/reset_i \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/start_crc_i \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/data_i \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/data_valid_i \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/crc_o \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/crc \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/crc_r \
		/can_bus_controller_tb/u_dut/u_can_crc_gen/data \
	)
add wave -vgroup {Fast VC} \
	/can_bus_controller_tb/u_can_bus_node_fast/can_bus_io \
	/can_bus_controller_tb/u_can_bus_node_fast/trans_rx_rec_io \
	/can_bus_controller_tb/u_can_bus_node_fast/trans_tx_rec_io \
	/can_bus_controller_tb/u_can_bus_node_fast/sending \
	/can_bus_controller_tb/u_can_bus_node_fast/tx \
	/can_bus_controller_tb/u_can_bus_node_fast/tx_from_tx \
	/can_bus_controller_tb/u_can_bus_node_fast/tx_from_rx \
	/can_bus_controller_tb/u_can_bus_node_fast/rx \
	/can_bus_controller_tb/u_can_bus_node_fast/rx_to_rx \
	/can_bus_controller_tb/u_can_bus_node_fast/clk \
	/can_bus_controller_tb/u_can_bus_node_fast/gc_model_id_name \
	/can_bus_controller_tb/u_can_bus_node_fast/gc_clk_period \
	/can_bus_controller_tb/u_can_bus_node_fast/gc_clock_delta \
	( -vgroup TX \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/clk_i \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/tx_o \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/rx_i \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/sending_o \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/trans_rec_io \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/model_id \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/TransmitFifo \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/TransmitRequestCount \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/TransmitDoneCount \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/delay \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/gc_model_id_name \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/gc_clk_period \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/c_model_instance_name \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/bit_rate \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/prop_seq \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/phase_seg_1 \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/phase_seg_2 \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/RV \
	) \
	( -vgroup Transmitter \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_frame \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_frame_slv \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_param \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_arb_lost \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_bit_stuffing_dbg \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_sample_point_dbg \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_ack_received \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/crc \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/byte_end_index \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/frame_end_index \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/bit_stuffing_counter \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/previous_bit_value \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_rand_crc_index \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/v_enable_bit_suffing_error \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/bit_buffer \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/byte_start_index \
		/can_bus_controller_tb/u_can_bus_node_fast/u_tx/p_transmitter/crc_start_index \
	) \
	( -vgroup RX \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/clk_i \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/tx_o \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/rx_i \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/trans_rec_io \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/model_id \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/ReceiveFifo \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/ReceiveCount \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/disabled_rx \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/nack_packages \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/gc_model_id_name \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/gc_clk_period \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/c_model_instance_name \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/bit_rate \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/prop_seq \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/phase_seg_1 \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/phase_seg_2 \
	) \
	( -vgroup Receiver \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/v_frame \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/v_param \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/bit_stuffing_dbg \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/sample_point_dbg \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/sync_en \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/v_seg_1_end \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/crc_calc \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/crc_start_index \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/crc_received \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/can_frame_bit_size \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/bit_counter \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/data_bits_index \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/can_frame_rx_done \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/bit_buffer \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/data_length_bits \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/bit_stuffing_counter \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/previous_bit_value \
		/can_bus_controller_tb/u_can_bus_node_fast/u_rx/p_receiver/error_start \
	)
add wave -vgroup {Norm VC} \
	/can_bus_controller_tb/u_can_bus_node/can_bus_io \
	/can_bus_controller_tb/u_can_bus_node/trans_rx_rec_io \
	/can_bus_controller_tb/u_can_bus_node/trans_tx_rec_io \
	/can_bus_controller_tb/u_can_bus_node/sending \
	/can_bus_controller_tb/u_can_bus_node/tx \
	/can_bus_controller_tb/u_can_bus_node/tx_from_tx \
	/can_bus_controller_tb/u_can_bus_node/tx_from_rx \
	/can_bus_controller_tb/u_can_bus_node/rx \
	/can_bus_controller_tb/u_can_bus_node/rx_to_rx \
	/can_bus_controller_tb/u_can_bus_node/clk \
	/can_bus_controller_tb/u_can_bus_node/gc_model_id_name \
	/can_bus_controller_tb/u_can_bus_node/gc_clk_period \
	/can_bus_controller_tb/u_can_bus_node/gc_clock_delta \
	( -vgroup TX \
		/can_bus_controller_tb/u_can_bus_node/u_tx/clk_i \
		/can_bus_controller_tb/u_can_bus_node/u_tx/tx_o \
		/can_bus_controller_tb/u_can_bus_node/u_tx/rx_i \
		/can_bus_controller_tb/u_can_bus_node/u_tx/sending_o \
		/can_bus_controller_tb/u_can_bus_node/u_tx/trans_rec_io \
		/can_bus_controller_tb/u_can_bus_node/u_tx/model_id \
		/can_bus_controller_tb/u_can_bus_node/u_tx/TransmitFifo \
		/can_bus_controller_tb/u_can_bus_node/u_tx/TransmitRequestCount \
		/can_bus_controller_tb/u_can_bus_node/u_tx/TransmitDoneCount \
		/can_bus_controller_tb/u_can_bus_node/u_tx/delay \
		/can_bus_controller_tb/u_can_bus_node/u_tx/gc_model_id_name \
		/can_bus_controller_tb/u_can_bus_node/u_tx/gc_clk_period \
		/can_bus_controller_tb/u_can_bus_node/u_tx/c_model_instance_name \
		/can_bus_controller_tb/u_can_bus_node/u_tx/bit_rate \
		/can_bus_controller_tb/u_can_bus_node/u_tx/prop_seq \
		/can_bus_controller_tb/u_can_bus_node/u_tx/phase_seg_1 \
		/can_bus_controller_tb/u_can_bus_node/u_tx/phase_seg_2 \
		/can_bus_controller_tb/u_can_bus_node/u_tx/RV \
	) \
	( -vgroup Transmitter \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_frame \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_frame_slv \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_param \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_arb_lost \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_bit_stuffing_dbg \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_sample_point_dbg \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_ack_received \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/crc \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/byte_end_index \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/frame_end_index \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/bit_stuffing_counter \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/previous_bit_value \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_rand_crc_index \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/v_enable_bit_suffing_error \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/bit_buffer \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/byte_start_index \
		/can_bus_controller_tb/u_can_bus_node/u_tx/p_transmitter/crc_start_index \
	) \
	( -vgroup RX \
		/can_bus_controller_tb/u_can_bus_node/u_rx/clk_i \
		/can_bus_controller_tb/u_can_bus_node/u_rx/tx_o \
		/can_bus_controller_tb/u_can_bus_node/u_rx/rx_i \
		/can_bus_controller_tb/u_can_bus_node/u_rx/trans_rec_io \
		/can_bus_controller_tb/u_can_bus_node/u_rx/model_id \
		/can_bus_controller_tb/u_can_bus_node/u_rx/ReceiveFifo \
		/can_bus_controller_tb/u_can_bus_node/u_rx/ReceiveCount \
		/can_bus_controller_tb/u_can_bus_node/u_rx/disabled_rx \
		/can_bus_controller_tb/u_can_bus_node/u_rx/nack_packages \
		/can_bus_controller_tb/u_can_bus_node/u_rx/gc_model_id_name \
		/can_bus_controller_tb/u_can_bus_node/u_rx/gc_clk_period \
		/can_bus_controller_tb/u_can_bus_node/u_rx/c_model_instance_name \
		/can_bus_controller_tb/u_can_bus_node/u_rx/bit_rate \
		/can_bus_controller_tb/u_can_bus_node/u_rx/prop_seq \
		/can_bus_controller_tb/u_can_bus_node/u_rx/phase_seg_1 \
		/can_bus_controller_tb/u_can_bus_node/u_rx/phase_seg_2 \
	) \
	( -vgroup Receiver \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/v_frame \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/v_param \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/bit_stuffing_dbg \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/sample_point_dbg \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/sync_en \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/v_seg_1_end \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/crc_calc \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/crc_start_index \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/crc_received \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/can_frame_bit_size \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/bit_counter \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/data_bits_index \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/can_frame_rx_done \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/bit_buffer \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/data_length_bits \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/bit_stuffing_counter \
		/can_bus_controller_tb/u_can_bus_node/u_rx/p_receiver/previous_bit_value \
	)
add wave -vgroup {Slow VC} \
	/can_bus_controller_tb/u_can_bus_node_slow/can_bus_io \
	/can_bus_controller_tb/u_can_bus_node_slow/trans_rx_rec_io \
	/can_bus_controller_tb/u_can_bus_node_slow/trans_tx_rec_io \
	/can_bus_controller_tb/u_can_bus_node_slow/sending \
	/can_bus_controller_tb/u_can_bus_node_slow/tx \
	/can_bus_controller_tb/u_can_bus_node_slow/tx_from_tx \
	/can_bus_controller_tb/u_can_bus_node_slow/tx_from_rx \
	/can_bus_controller_tb/u_can_bus_node_slow/rx \
	/can_bus_controller_tb/u_can_bus_node_slow/rx_to_rx \
	/can_bus_controller_tb/u_can_bus_node_slow/clk \
	/can_bus_controller_tb/u_can_bus_node_slow/gc_model_id_name \
	/can_bus_controller_tb/u_can_bus_node_slow/gc_clk_period \
	/can_bus_controller_tb/u_can_bus_node_slow/gc_clock_delta \
	( -vgroup TX \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/clk_i \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/tx_o \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/rx_i \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/sending_o \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/trans_rec_io \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/model_id \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/TransmitFifo \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/TransmitRequestCount \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/TransmitDoneCount \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/delay \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/gc_model_id_name \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/gc_clk_period \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/c_model_instance_name \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/bit_rate \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/prop_seq \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/phase_seg_1 \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/phase_seg_2 \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/RV \
	) \
	( -vgroup Transmitter \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_frame \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_frame_slv \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_param \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_arb_lost \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_bit_stuffing_dbg \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_sample_point_dbg \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_ack_received \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/crc \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/byte_end_index \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/frame_end_index \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/bit_stuffing_counter \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/previous_bit_value \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_rand_crc_index \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/v_enable_bit_suffing_error \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/bit_buffer \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/byte_start_index \
		/can_bus_controller_tb/u_can_bus_node_slow/u_tx/p_transmitter/crc_start_index \
	) \
	( -vgroup RX \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/clk_i \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/tx_o \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/rx_i \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/trans_rec_io \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/model_id \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/ReceiveFifo \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/ReceiveCount \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/disabled_rx \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/nack_packages \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/gc_model_id_name \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/gc_clk_period \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/c_model_instance_name \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/bit_rate \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/prop_seq \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/phase_seg_1 \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/phase_seg_2 \
	) \
	( -vgroup Receiver \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/v_frame \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/v_param \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/bit_stuffing_dbg \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/sample_point_dbg \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/sync_en \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/v_seg_1_end \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/crc_calc \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/crc_start_index \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/crc_received \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/can_frame_bit_size \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/bit_counter \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/data_bits_index \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/can_frame_rx_done \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/bit_buffer \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/data_length_bits \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/bit_stuffing_counter \
		/can_bus_controller_tb/u_can_bus_node_slow/u_rx/p_receiver/previous_bit_value \
	)
add wave -vgroup {Dut 2} \
	/can_bus_controller_tb/u_dut_2/clk_i \
	/can_bus_controller_tb/u_dut_2/reset_i \
	/can_bus_controller_tb/u_dut_2/can_reset_i \
	/can_bus_controller_tb/u_dut_2/rx_i \
	/can_bus_controller_tb/u_dut_2/tx_o \
	/can_bus_controller_tb/u_dut_2/src_s2d_o \
	/can_bus_controller_tb/u_dut_2/src_d2s_i \
	/can_bus_controller_tb/u_dut_2/sink_s2d_i \
	/can_bus_controller_tb/u_dut_2/sink_d2s_o \
	/can_bus_controller_tb/u_dut_2/ack_o \
	/can_bus_controller_tb/u_dut_2/ns_o \
	/can_bus_controller_tb/u_dut_2/debug_error_flag_o \
	/can_bus_controller_tb/u_dut_2/stuff_bit \
	/can_bus_controller_tb/u_dut_2/stuff_bit_valid \
	/can_bus_controller_tb/u_dut_2/crc \
	/can_bus_controller_tb/u_dut_2/crc_start \
	/can_bus_controller_tb/u_dut_2/sta_reset \
	/can_bus_controller_tb/u_dut_2/sta_ack \
	/can_bus_controller_tb/u_dut_2/ats_ready \
	/can_bus_controller_tb/u_dut_2/frame_bit \
	/can_bus_controller_tb/u_dut_2/ats_valid \
	/can_bus_controller_tb/u_dut_2/ats_reset \
	/can_bus_controller_tb/u_dut_2/ide \
	/can_bus_controller_tb/u_dut_2/rtr \
	/can_bus_controller_tb/u_dut_2/dlc \
	/can_bus_controller_tb/u_dut_2/sample_rx_valid \
	/can_bus_controller_tb/u_dut_2/frame_in_progress \
	/can_bus_controller_tb/u_dut_2/sample_rx \
	/can_bus_controller_tb/u_dut_2/transmit \
	/can_bus_controller_tb/u_dut_2/is_transmitter \
	/can_bus_controller_tb/u_dut_2/can_node_clk_reset \
	/can_bus_controller_tb/u_dut_2/rx_sync \
	/can_bus_controller_tb/u_dut_2/~ANONYMOUS~0 \
	/can_bus_controller_tb/u_dut_2/~ANONYMOUS~1 \
	/can_bus_controller_tb/u_dut_2/~ANONYMOUS~2 \
	/can_bus_controller_tb/u_dut_2/gc_bit_rate_hz \
	/can_bus_controller_tb/u_dut_2/gc_default_prop_seg_length \
	/can_bus_controller_tb/u_dut_2/gc_default_phase_seg_1_length \
	/can_bus_controller_tb/u_dut_2/gc_default_phase_seg_2_length \
	/can_bus_controller_tb/u_dut_2/gc_sync_jump_width \
	/can_bus_controller_tb/u_dut_2/c_crc_width \
	/can_bus_controller_tb/u_dut_2/c_crc_poly \
	/can_bus_controller_tb/u_dut_2/c_crc_init \
	/can_bus_controller_tb/u_dut_2/c_crc_xor \
	/can_bus_controller_tb/u_dut_2/c_crc_data_width
add wave -expand -vgroup {Dut Fsm 2} \
	/can_bus_controller_tb/u_dut_2/u_fsm/clk_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/reset_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/can_reset_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/rx_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/tx_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/ack_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/ns_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/stuff_bit_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/stuff_bit_valid_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/frame_in_progress_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/crc_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/crc_start_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/sample_rx_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/transmit_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/can_node_clk_reset_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/sta_reset_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/sta_ack_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/ast_ready_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/is_transmitter_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/frame_bit_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/frame_bit_valid_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/ide_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/rtr_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/dlc_i \
	/can_bus_controller_tb/u_dut_2/u_fsm/ats_reset_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/debug_error_flag_o \
	/can_bus_controller_tb/u_dut_2/u_fsm/fsm_state \
	/can_bus_controller_tb/u_dut_2/u_fsm/node_error_state \
	/can_bus_controller_tb/u_dut_2/u_fsm/transmit_error_count \
	/can_bus_controller_tb/u_dut_2/u_fsm/receive_error_count \
	/can_bus_controller_tb/u_dut_2/u_fsm/bus_off_re_int_count \
	/can_bus_controller_tb/u_dut_2/u_fsm/bit_count \
	/can_bus_controller_tb/u_dut_2/u_fsm/transmit_ack \
	/can_bus_controller_tb/u_dut_2/u_fsm/is_transmitter \
	/can_bus_controller_tb/u_dut_2/u_fsm/go_to_suspended \
	/can_bus_controller_tb/u_dut_2/u_fsm/dlc_shift \
	/can_bus_controller_tb/u_dut_2/u_fsm/rtr_bit \
	/can_bus_controller_tb/u_dut_2/u_fsm/crc_error \
	/can_bus_controller_tb/u_dut_2/u_fsm/stuff_bit_error \
	/can_bus_controller_tb/u_dut_2/u_fsm/do_not_count_stuff_error \
	/can_bus_controller_tb/u_dut_2/u_fsm/ack_error \
	/can_bus_controller_tb/u_dut_2/u_fsm/tec_control \
	/can_bus_controller_tb/u_dut_2/u_fsm/rec_control \
	/can_bus_controller_tb/u_dut_2/u_fsm/rx_r \
	/can_bus_controller_tb/u_dut_2/u_fsm/c_bit_count_into_crc \
	/can_bus_controller_tb/u_dut_2/u_fsm/c_bit_count_into_arb
wv.cursors.add -time 431600ns -name {Default cursor}
wv.cursors.setactive -name {Default cursor}
wv.cursors.subcursor.add -time 1169931025ps -name {Cursor 1}
wv.cursors.setactive -name {Default cursor}
wv.zoom.range -from 0fs -to 1974400ns
wv.time.unit.auto.set
transcript $curr_transcript
